stages:
  - build
  - lint
  - test
  - reporting
  - package
  - deploy

variables:
  # KUBE_CONTEXT: usernameorgroupname/agentconfigprojectname:agentname
  KUBE_CONTEXT: gabrielbenabou/bimdb:bimdb-pm4-init-lab
  # == SAST Variables ==
  # SCAN_KUBERNETES_MANIFESTS: "true"
  SEARCH_MAX_DEPTH: 10
  SAST_SEMGREP_METRICS: "false"
  # == Secret Detection Variables ==
  SECRET_DETECTION_EXCLUDED_PATHS: ${SAST_EXCLUDED_PATHS}

  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  # For further reference see: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Maven.gitlab-ci.yml
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true

default:
  tags:
    - pm4-runner-1

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .m2/repository

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - local: .gitlab/pipeline_templates/*.yml
