namespace: ""

environment: ""

backend:
  appName: bimdb-backend
  replicas: 1
  imageTag: ""
  containerPort: 8080
  exposedPort: 80
  env:
    TMDB_API_KEY: ""
    ACTIVE_PROFILES: ""
    OAUTH2_JWK_URI: ""


frontend:
  appName: bimdb-frontend
  replicas: 1
  imageTag: ""
  containerPort: 80
  exposedPort: 80

db:
  iam:
    appName: bimdb-iam-database
    replicas: 1
    imageTag: 15
    containerPort: 5432
    storageSize: 10Gi
    userName: postgres
    userPassword: ""
    databaseName: keycloak
  bimdb:
    appName: bimdb-database
    replicas: 1
    imageTag: 15
    containerPort: 5432
    storageSize: 10Gi
    userName: postgres
    userPassword: ""
    databaseName: bimdb

iam:
  appName: bimdb-auth
  userName: admin
  userPassword: ""
  imageTag: 21.1.1
  containerPort: 8080
  exposedPort: 80