namespace: ""

environment: ""

backend:
  appName: bimdb-backend
  replicas: 1
  imageTag: ""
  containerPort: 8080
  exposedPort: 80

frontend:
  appName: bimdb-frontend
  replicas: 1
  imageTag: ""
  containerPort: 80
  exposedPort: 80

db:
  appName: bimdb-database
  replicas: 1
  imageTag: 15
  containerPort: 5432
  storageSize: 10Gi
  userName: postgres
  userPassword: ""
  databaseName: bimdb
