.kube-context:
  before_script:
  - if [ -n "$KUBE_CONTEXT" ]; then kubectl config use-context "$KUBE_CONTEXT"; fi

kubernetes-connectivity-test:
  stage: deploy
  extends: [.kube-context]
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl get pods -n gitlab
    - kubectl get pods -n betterimdb-stage
  when: manual