pages:
  stage: deploy
  image:
    name: squidfunk/mkdocs-material
    entrypoint: [""]
  script:
    - mkdocs build --verbose --config-file mkdocs.yml --site-dir public
  artifacts:
    paths:
      - public
  environment:
    name: Wiki
    url: "https://$CI_PROJECT_NAMESPACE.gitlab.io/$CI_PROJECT_NAME/"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME == "development"
      changes:
        - docs/**/*
