apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.iam.appName }}-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  userName: {{ .Values.db.iam.userName }}
  databaseName: {{ .Values.db.iam.databaseName }}
  userPassword: {{ .Values.db.iam.userPassword | b64enc }}