apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.bimdb.appName }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: "cinder-csi-ssd"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.bimdb.storageSize }}