apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.iam.appName }}-deployment"
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.iam.appName }}-deployment"
  template:
    metadata:
      labels:
        app: "{{ .Values.iam.appName }}-deployment"
    spec:
      containers:
      - name: {{ .Values.iam.appName }}-deployment
        image: "quay.io/keycloak/keycloak:{{ .Values.backend.imageTag }}"
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          value: {{ .Values.iam.userName }}
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: {{ .Values.iam.userPassword }}
        - name: DB_VENDOR
          value: postgres
        - name: DB_ADDR
          value: {{ .Values.db.iam.appName }}-service
        - name: DB_PORT
          value: "{{ .Values.db.iam.containerPort }}"
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.iam.appName }}-credentials
              key: databaseName
        - name: DB_SCHEMA
          value: public
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.iam.appName }}-credentials
              key: userName
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.iam.appName }}-credentials
              key: userPassword
        - name: KC_PROXY
          value: "edge"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
