apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.backend.appName }}-deployment"
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.backend.appName }}-deployment"
  template:
    metadata:
      labels:
        app: "{{ .Values.backend.appName }}-deployment"
    spec:
      containers:
        - name: "{{ .Values.backend.appName }}-deployment"
          image: "registry.gitlab.com/gabrielbenabou/bimdb:{{ .Values.backend.imageTag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{.Values.backend.containerPort}}
          env:
            - name: TMDB_API_KEY
              value: {{.Values.backend.env.TMDB_API_KEY}}
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: {{ .Values.db.bimdb.appName }}-service
            - name: DB_PORT
              value: "{{ .Values.db.bimdb.containerPort }}"
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.bimdb.appName }}-credentials
                  key: databaseName
            - name: DB_SCHEMA
              value: public
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.bimdb.appName }}-credentials
                  key: userName
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.bimdb.appName }}-credentials
                  key: userPassword
