apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.bimdb.appName }}-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  userName: {{ .Values.db.bimdb.userName }}
  databaseName: {{ .Values.db.bimdb.databaseName }}
  userPassword: {{ .Values.db.bimdb.userPassword | b64enc }}